name: Run Python Tests
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WITH_INTEGRATION: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install pip and poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Run tests
        run: |
          poetry install
          poetry run pytest --cov=admin_webapp
      # - name: linter
      #   run: |
      #     pip install pylint
      #     ./tests/lint.sh admin_webapp
      - name: style check
        run: |
          pip install pydocstyle
          ./tests/style.sh admin_webapp


